FROM nginx
RUN apt-get update -qq && apt-get -y install apache2-utils
ENV RAILS_ROOT /var/www/devops-rails-example
WORKDIR $RAILS_ROOT
RUN mkdir log
COPY public public/
COPY config/containers/nginx.conf /tmp/devops-rails-example.nginx
RUN envsubst '$RAILS_ROOT' < /tmp/devops-rails-example.nginx > /etc/nginx/conf.d/default.conf
CMD [ "nginx", "-g", "daemon off;" ]
